// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteItem(arg1:number):Promise<void>;

export function GetAllItems():Promise<Array<models.Item>>;

export function GetItemByID(arg1:number):Promise<models.Item>;

export function GetItemStats():Promise<Record<string, number>>;

export function GetItemsByLanguage(arg1:string):Promise<Array<models.Item>>;

export function GetItemsByType(arg1:string):Promise<Array<models.Item>>;

export function GetUniqueLanguages():Promise<Array<string>>;

export function SaveItem(arg1:models.Item):Promise<number>;

export function SearchItems(arg1:string,arg2:string):Promise<Array<models.Item>>;

export function UpdateItem(arg1:models.Item):Promise<void>;
