// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetAllItems() {
  return window['go']['main']['App']['GetAllItems']();
}

export function GetItemByID(arg1) {
  return window['go']['main']['App']['GetItemByID'](arg1);
}

export function GetItemStats() {
  return window['go']['main']['App']['GetItemStats']();
}

export function GetItemsByLanguage(arg1) {
  return window['go']['main']['App']['GetItemsByLanguage'](arg1);
}

export function GetItemsByType(arg1) {
  return window['go']['main']['App']['GetItemsByType'](arg1);
}

export function GetUniqueLanguages() {
  return window['go']['main']['App']['GetUniqueLanguages']();
}

export function SaveItem(arg1) {
  return window['go']['main']['App']['SaveItem'](arg1);
}

export function SearchItems(arg1, arg2) {
  return window['go']['main']['App']['SearchItems'](arg1, arg2);
}

export function UpdateItem(arg1) {
  return window['go']['main']['App']['UpdateItem'](arg1);
}
